spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Solicitudes Service Routes
        - id: solicitudes-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/solicitudes/**
          filters:
            - StripPrefix=1

        # Logistica Service Routes
        - id: logistica-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/logistica/**
          filters:
            - StripPrefix=1

        # Tarifas Service Routes
        - id: tarifas-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/tarifas/**
          filters:
            - StripPrefix=1

        # Tracking Service Routes
        - id: tracking-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/tracking/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/transportista-realm
          jwk-set-uri: http://localhost:8080/realms/transportista-realm/protocol/openid-connect/certs

server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
